//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int Id_Cita { get; set; }
        public string Cedula_Usuario { get; set; }
        public System.DateTime Fecha_Cita { get; set; }
        public System.TimeSpan Hora_Cita { get; set; }
        public int Id_TipoEspecialista { get; set; }
        public string Cedula_Especialista { get; set; }
        public int Id_EstadoCita { get; set; }
        public string Estado { get; set; }
        public string UsuarioCreador { get; set; }
        public string FechaCreacion { get; set; }
        public string UsuarioModificador { get; set; }
        public string FechaModificacion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Parametro Parametro { get; set; }
        public virtual Parametro Parametro1 { get; set; }
    }
}
