//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesoHistorialLog
    {
        public int Id_Log { get; set; }
        public string Usuario { get; set; }
        public string Rol { get; set; }
        public string Cedula_Cliente { get; set; }
        public System.DateTime FechaIntento { get; set; }
        public string Resultado { get; set; }
    }
}
