//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertaSeguimiento
    {
        public int Id_Alerta { get; set; }
        public string Cedula_Cliente { get; set; }
        public System.DateTime FechaAlerta { get; set; }
        public string TipoAlerta { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string ConfiguradaPor { get; set; }
        public System.DateTime FechaConfiguracion { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string MedioEnvio { get; set; }
        public Nullable<bool> Enviada { get; set; }
    }
}
