//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaniaMetrica
    {
        public int Id_Campania { get; set; }
        public string Cedula_Cliente { get; set; }
        public Nullable<bool> Abierto { get; set; }
        public Nullable<bool> Click { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<bool> Automatica { get; set; }
    
        public virtual CampaniaMarketing CampaniaMarketing { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
