//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaniaCliente
    {
        public int Id_Campania { get; set; }
        public string Cedula_Cliente { get; set; }
        public string Correo_Cliente { get; set; }
        public string Estado { get; set; }
        public string UsuarioCreador { get; set; }
        public string FechaCreacion { get; set; }
        public string UsuarioModificador { get; set; }
        public string FechaModificacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual CampaniaMarketing CampaniaMarketing { get; set; }
    }
}
