//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionRecurrencia
    {
        public int Id { get; set; }
        public int UmbralCompras { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    }
}
