//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriteriosPromocionRecurrente
    {
        public int Id { get; set; }
        public int MinimoCompras { get; set; }
        public int DiasRango { get; set; }
        public string UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificador { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
