//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int Id_Detalle { get; set; }
        public Nullable<int> Id_Venta { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual Inventario Inventario { get; set; }
        public virtual PuntoVenta PuntoVenta { get; set; }
    }
}
