//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialCambiosCliente
    {
        public int Id { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Genero { get; set; }
        public string Padecimiento { get; set; }
        public string Numero_Telefono { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public string UsuarioModificador { get; set; }
    }
}
