//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialCliente
    {
        public int Id_Historial { get; set; }
        public string Cedula_Cliente { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Antecedentes { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public string Observaciones { get; set; }
        public string Usuario_Registro { get; set; }
    }
}
