//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntentoAccesoHistorial
    {
        public int Id { get; set; }
        public string CedulaCliente { get; set; }
        public Nullable<System.DateTime> FechaIntento { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> RolUsuario { get; set; }
        public string Motivo { get; set; }
        public Nullable<bool> AccesoAutorizado { get; set; }
    }
}
