//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaSegmentadaCliente
    {
        public int Id_ListaCliente { get; set; }
        public Nullable<int> Id_Lista { get; set; }
        public string Cedula_Cliente { get; set; }
    
        public virtual ListaSegmentada ListaSegmentada { get; set; }
    }
}
