//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaSegmentada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListaSegmentada()
        {
            this.ListaSegmentadaCliente = new HashSet<ListaSegmentadaCliente>();
        }
    
        public int Id_Lista { get; set; }
        public string NombreLista { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Nombre { get; set; }
        public string UsuarioCreador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaSegmentadaCliente> ListaSegmentadaCliente { get; set; }
    }
}
