//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSistema
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Modulo { get; set; }
        public string Mensaje { get; set; }
        public string Usuario { get; set; }
    }
}
