//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaCredito()
        {
            this.PagoCredito = new HashSet<PagoCredito>();
        }
    
        public int Id_NotaCredito { get; set; }
        public string Cedula_Cliente { get; set; }
        public decimal MontoOtorgado { get; set; }
        public decimal SaldoPendiente { get; set; }
        public System.DateTime FechaOtorgado { get; set; }
        public Nullable<System.DateTime> FechaUltimoPago { get; set; }
        public string Estado { get; set; }
        public string UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificador { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Id_Venta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual PuntoVenta PuntoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoCredito> PagoCredito { get; set; }
    }
}
