//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoCredito
    {
        public int Id_PagoCredito { get; set; }
        public int Id_NotaCredito { get; set; }
        public decimal Monto { get; set; }
        public string Metodo { get; set; }
        public System.DateTime FechaPago { get; set; }
    
        public virtual NotaCredito NotaCredito { get; set; }
    }
}
