//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoVenta
    {
        public int Id_Pago { get; set; }
        public Nullable<int> Id_Venta { get; set; }
        public string Metodo { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual PuntoVenta PuntoVenta { get; set; }
    }
}
