//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PuntoVenta()
        {
            this.Contabilidad = new HashSet<Contabilidad>();
        }
    
        public int Id_Venta { get; set; }
        public int Id_Producto { get; set; }
        public string Cedula_Cliente { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public int Id_MetodoPago { get; set; }
        public DateTime Fecha_Venta { get; set; }
        public String Hora_Venta { get; set; }
        public string Estado { get; set; }
        public string UsuarioCreador { get; set; }
        public string FechaCreacion { get; set; }
        public string UsuarioModificador { get; set; }
        public string FechaModificacion { get; set; }
        public string NombreEmpleado { get; set; }

        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contabilidad> Contabilidad { get; set; }
        public virtual Inventario Inventario { get; set; }
        public virtual Parametro Parametro { get; set; }
    }
}
