//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaSimulada
    {
        public int Id_Tarjeta { get; set; }
        public string NumeroTarjeta { get; set; }
        public string NombreTitular { get; set; }
        public string FechaVencimiento { get; set; }
        public string CVV { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
