//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDOpticasJAVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaPromocion
    {
        public int Id_VentaPromocion { get; set; }
        public int Id_Venta { get; set; }
        public int Id_Campania { get; set; }
        public decimal MontoDescuento { get; set; }
        public string CodigoPromo { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public string UsuarioAplicacion { get; set; }
    
        public virtual CampaniaMarketing CampaniaMarketing { get; set; }
        public virtual PuntoVenta PuntoVenta { get; set; }
    }
}
